services:
  - type: web
    name: medical-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false